In [5]:
#1
import numpy as np
arr = np.random.randint(low = 10, high = 50, size = 20)
#print(arr)
mean = np.mean(arr)
std = np.std(arr)
print(f"mean {mean},standard deviation {std}")

mean 26.0,standard deviation 11.60172400981854


In [12]:
#2
arr = np.random.rand(6, 5)
print(arr)
arr1 = arr.reshape(5,6)
print(arr1)

[[0.54249449 0.02202062 0.11202848 0.58511248 0.79118384]
 [0.49520222 0.784711   0.24762209 0.62793824 0.01710447]
 [0.09724181 0.12636858 0.97720034 0.00964201 0.78217924]
 [0.91907769 0.06333866 0.54451639 0.35322146 0.1045287 ]
 [0.07935292 0.39139657 0.62199456 0.48272185 0.33832153]
 [0.46753874 0.2890836  0.00187676 0.96572099 0.44033899]]
[[0.54249449 0.02202062 0.11202848 0.58511248 0.79118384 0.49520222]
 [0.784711   0.24762209 0.62793824 0.01710447 0.09724181 0.12636858]
 [0.97720034 0.00964201 0.78217924 0.91907769 0.06333866 0.54451639]
 [0.35322146 0.1045287  0.07935292 0.39139657 0.62199456 0.48272185]
 [0.33832153 0.46753874 0.2890836  0.00187676 0.96572099 0.44033899]]


In [16]:
#3
arr = np.arange(1,26).reshape(5,5)
print(arr)
arr[2:,1:4]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [33]:
#4
A = np.random.randint(low = 1, high = 100, size = 10)
B = np.random.randint(low = 1, high = 100, size = 10)

sum_arr = A+B
print(sum_arr)
print(sum_arr*2)

[139 166  50  86  84  61 156 100  95  18]
[278 332 100 172 168 122 312 200 190  36]


In [34]:
#5
A = np.random.randint(low = 1, high = 10, size = (3,4))
B = np.array([1, 2, 3, 4]).reshape(4,)
sum_arr = arr1+arr2
print(sum_arr)


[[ 5  7  6 11]
 [10 11  7 10]
 [ 6  8  8  6]]


In [46]:
#6
arr = np.random.randint(low = 1, high = 100, size = (3,3))
print(arr)

# Find the row with the maximum sum
sum_row = arr.sum(axis=1)
print("sum of each row =",sum_row)
max_row_index = np.argmax(sum_row)
print("Index of Row with max sum = ",max_row_index)
max_value = np.max(arr[max_row_index])
print("Maximum value in the row with max sum = ",max_value)

[[93  7 45]
 [ 1 75 67]
 [ 6 90 37]]
sum of each row = [145 143 133]
Index of Row with max sum =  0
Maximum value in the row with max sum =  93


In [53]:
#7
A = np.random.randint(1,10,(2,2))
B = np.random.randint(1,10,(2,2))
print(" A =",A)
print(" B =",B)
dot_pdt = np.dot(A,B)
print("Dot product of A.B = ",dot_pdt)

 A = [[5 3]
 [2 7]]
 B = [[6 9]
 [3 9]]
Dot product of A.B =  [[39 72]
 [33 81]]


In [54]:
#8
A = np.random.randint(1,50,(6,6))
print(A)
A[(A>25)]


[[43 26 27  1 36 32]
 [ 9 30 10  6 14 38]
 [28  7 35  4 26 20]
 [ 6  7 16 15  3  4]
 [34 26 49 45 25 42]
 [25 43  9 46 14  1]]


array([43, 26, 27, 36, 32, 30, 38, 28, 35, 26, 34, 26, 49, 45, 42, 43, 46],
      dtype=int32)

In [55]:
#9
arr = np.random.rand(5, 5)
print(arr)
print("median along the columns ",np.median(arr,axis =0))
print("median along the rows ",np.median(arr,axis =1))
print("Variance along the columns ",np.var(arr,axis =0))
print("Variance along the rows ",np.var(arr,axis =1))


[[0.68601833 0.76441954 0.34623097 0.85685079 0.45400563]
 [0.8190774  0.52041731 0.88096804 0.87135967 0.56948376]
 [0.08108598 0.46742884 0.94398194 0.4285735  0.32584745]
 [0.002565   0.15863606 0.70094912 0.88025788 0.97318946]
 [0.96403286 0.44575298 0.67300539 0.49216393 0.00468565]]
median along the columns  [0.68601833 0.46742884 0.70094912 0.85685079 0.45400563]
median along the rows  [0.68601833 0.8190774  0.4285735  0.70094912 0.49216393]
Variance along the columns  [0.15482262 0.03735159 0.04355026 0.04063136 0.1001092 ]
Variance along the rows  [0.0367612  0.0240747  0.0792581  0.15271187 0.09846586]


In [66]:
#10
A = np.random.randint(1,10,(3,3))
print(A)
print("Result after subracting 2 from each element",A-2)
square_matrix = np.square(A-2.1)
print("Result after squaring each element",square_matrix)
print("Reciprocal",np.reciprocal(square_matrix))

[[7 5 6]
 [2 1 1]
 [9 5 7]]
Result after subracting 2 from each element [[ 5  3  4]
 [ 0 -1 -1]
 [ 7  3  5]]
Result after squaring each element [[2.401e+01 8.410e+00 1.521e+01]
 [1.000e-02 1.210e+00 1.210e+00]
 [4.761e+01 8.410e+00 2.401e+01]]
Reciprocal [[4.16493128e-02 1.18906064e-01 6.57462196e-02]
 [1.00000000e+02 8.26446281e-01 8.26446281e-01]
 [2.10039908e-02 1.18906064e-01 4.16493128e-02]]


In [70]:
#PANDAS
#1
import pandas as pd

df = pd.read_csv("auto-mpg.csv")
df.head(10)


mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  
5       1           ford galaxie 500  
6       1           chevrolet impala  
7       1          plymouth fury iii  
8       1           pontiac catalina  
9       1         amc ambassador dpl

In [71]:
df.shape

(398, 9)

In [72]:
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [75]:
#2
#Filtering and indexing

filtered_df = df[(df['model year'] == 75) & (df['weight'] < 3000)][['car name', 'weight', 'mpg']]
print(filtered_df)


              car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0


In [76]:
#3 missing values
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [77]:
df["horsepower"].unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '?', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [87]:
#horsepower_median = df['horsepower'].median(numeric_only=True)
#print(horsepower_median)
#df['horsepower'] = df['horsepower'].replace('?', horsepower_median)
#print(df)
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')
median_value = df['horsepower'].median(numeric_only=True)
df['horsepower'] = df['horsepower'].replace('?', median_value )
print(df['horsepower'] )


0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...  
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 398, dtype: float64


In [89]:
# 4 Calculate power-to-weight ratio
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']
print(df)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin                   car name  power_to_weight_ratio  
0            70       1  chevrolet chevelle malibu         

In [90]:
#5
mean_mpg_by_origin = df.groupby('origin')['mpg'].mean()
print(mean_mpg_by_origin)

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64


In [91]:
#6
top_10_mpg = df.sort_values(by='mpg', ascending=False).head(10)
print(top_10_mpg)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0        65.0    2110          17.9   
329  44.6          4          91.0        67.0    1850          13.8   
325  44.3          4          90.0        48.0    2085          21.7   
394  44.0          4          97.0        52.0    2130          24.6   
326  43.4          4          90.0        48.0    2335          23.7   
244  43.1          4          90.0        48.0    1985          21.5   
309  41.5          4          98.0        76.0    2144          14.7   
330  40.9          4          85.0         NaN    1835          17.3   
324  40.8          4          85.0        65.0    2110          19.2   
247  39.4          4          85.0        70.0    2070          18.6   

     model year  origin                         car name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl   
325          80       2    

In [92]:
#7
# Define the custom function
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

# Apply function to each row and create the new column
df['performance_score'] = df.apply(performance_score, axis=1)

print(df)


      mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin                   car name  power_to_weight_ratio  \
0            70       1  chevrolet chevelle malibu        

In [95]:
#8
# Group by 'model_year' and calculate the mean for mpg, weight, and horsepower
summary_df = df.groupby('model year')[['mpg', 'weight', 'horsepower']].mean()
print(summary_df)

                  mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  107.037037
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.230769
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   77.481481
81          30.334483  2522.931034   81.035714
82          31.709677  2453.548387   81.466667


In [96]:
#9

# Filter cars with mpg > 30
high_mpg_cars = df[df['mpg'] > 30][['mpg', 'cylinders', 'horsepower', 'weight']]
# Display result
print(high_mpg_cars)
# Save to CSV
high_mpg_cars.to_csv('high_mpg_cars.csv', index=False)



      mpg  cylinders  horsepower  weight
53   31.0          4        65.0    1773
54   35.0          4        69.0    1613
129  31.0          4        67.0    1950
131  32.0          4        65.0    1836
144  31.0          4        52.0    1649
..    ...        ...         ...     ...
390  32.0          4        96.0    2665
391  36.0          4        84.0    2370
394  44.0          4        52.0    2130
395  32.0          4        84.0    2295
397  31.0          4        82.0    2720

[85 rows x 4 columns]


In [100]:
#10
# Step 1: Calculate Q1, Q3, and IQR
Q1 = df['mpg'].quantile(0.25)  # 25th percentile
Q3 = df['mpg'].quantile(0.75)  # 75th percentile
IQR = Q3 - Q1  # Interquartile Range
print("Q1 :",Q1)
print("Q2 :",Q3)
print("Interquartile Range :",IQR)

# Step 2: Define Outlier Thresholds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Lower bound :{lower_bound}\nUpper bound :{upper_bound}")

# Step 3: Identify Outliers
outliers = df[(df['mpg'] < lower_bound) | (df['mpg'] > upper_bound)]


# Step 4: Select Relevant Columns
outlier_df = outliers[['car name', 'mpg', 'model year']]

# Display Outliers
print(outlier_df)

Q1 : 17.5
Q2 : 29.0
Interquartile Range : 11.5
Lower bound :0.25
Upper bound :46.25
      car name   mpg  model year
322  mazda glc  46.6          80
